# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому перешел на этот плагин. Он тоже хорош :-)

# Создаем Продавца
POST http://localhost:8000/api/v1/sellers/ HTTP/1.1
content-type: application/json

{
    "first_name": "Ivan",
    "last_name": "Ivanov",
    "password": "104iii",
    "email": "iii@mts.ru"
}

###

# Получаем информацию о Продавце по его ИД
GET http://localhost:8000/api/v1/sellers/1 HTTP/1.1

###

# Получаем список Продавцов
GET http://localhost:8000/api/v1/sellers/ HTTP/1.1

###

# Создаем книгу
POST http://localhost:8000/api/v1/books/ HTTP/1.1
content-type: application/json

{
    "title": "Simple Code",
    "author": "Robert Martin",
    "pages": 177,
    "year": 2011,
    "seller_id": 2
}

###

# Получаем список книг
GET http://localhost:8000/api/v1/books/ HTTP/1.1

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/4 HTTP/1.1

###

# Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/1 HTTP/1.1
content-type: application/json

{
    "title": "Code",
    "author": "Robert Martin",
    "pages": 121,
    "year": 2008,
    "seller_id": 6
}

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/3 HTTP/1.1
content-type: application/json

###

# Обновляем поля в данных о Продавце
PUT http://localhost:8000/api/v1/sellers/3 HTTP/1.1
content-type: application/json

{
    "first_name": "Ivan",
    "last_name": "Ivanov-Petrov",
    "password": "104aaa",
    "email": "iii@mts.ru"
}

###

# Удаляем Продавца
DELETE http://localhost:8000/api/v1/sellers/2 HTTP/1.1
content-type: application/json

###